# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43d02666d413542760b2c2357e12226b540efaf9e9a4c0f9dd08f7383fcf2094fdff6cd011beefaa7184c5601d70b243a6140ffc6e7323e180dfb3b49f002d24

test:
  secret_key_base: b18cfcfdc7989b7b65bdcfe72243dae95b85a970c798c4f89034afc45db557c39945a96bd51aab87be8825b7ff8ce81bd21d05f5fe0721898b469fd8b0213835

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
